### ISSUE TITLE
Can't get stream control: Invalid mode (-51)

### ISSUE THREAD

**Issue by ghost** [themrx/PupilCaptureCPP#2]
Hello,

I am running your code using opencv 3.3 and vc14 to get camera output from the 200Hz Pupil Labs AR/VR Add-on. But get the error: Can't get stream control: Invalid mode (-51).  I tried reducing the resolution to 192x192 and got the project to run but then got locked up on Can't grab frame. Is there a reason this is happening?

**Comment by aplopski** [comment]
I have not worked with the 200Hz module, so I cannot be sure what is causing this. Looking at the error, it has to do with UVC. You could try changing the format from compressed to uncompressed, or see what Pupil is using now when grabbing frames.

I may be able to test with the 200Hz cameras in 1-2 weeks and see if I get the same issue.

**Comment by ghost** [comment]
That's great. I'll post up if it works.

**Comment by ghost** [comment]
Turns out it worked as is. Problem was, as you mentioned in readme.md, related to an error with memcpy so using the other pre-built uvc_8 folder rendered it perfectly. Thanks!
